// examples/06-react-microphone/src/app.tsx
import BpmAnalyzer from './components/BpmAnalyzer';
import './App.css';

function App() {
  return (
    <div className="app">
      <div className="container">
        <header>
          <h1>🎵 BPM Analyzer</h1>
          <p className="subtitle">Analyze BPM from microphone input in real-time</p>
        </header>
        <BpmAnalyzer />
      </div>
    </div>
  );
}

export default App;

// examples/09-vue-microphone/src/app.vue
<script setup lang="ts">
import BpmAnalyzer from './components/bpm-analyzer.vue';
</script>

<template>
  <div class="container">
    <header>
      <h1>🎵 BPM Analyzer</h1>
      <p class="subtitle">Analyze BPM from microphone input in real-time</p>
    </header>
    <BpmAnalyzer />
  </div>
</template>
